branches:
  # whitelist
  only:
    - master
    - Development

  # blacklist
  except:
    - gh-pages
     
before_build:
    - nuget restore
  
build:
  parallel: true
  project: HellionExtendedServer_Solution.sln      
  include_nuget_references: true 
